### ISSUE TITLE
Plugin appends to old .htaccess file in build directory rather than overwriting

### ISSUE THREAD

**Issue by timmb** [GatsbyCentral/gatsby-plugin-htaccess-redirects#10] opened 2022-04-07 15:45 UTC
When I do a `gatsby build` and then modify my project and do another `gatsby build` I end up with an unusable `.htaccess` file.

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule ^oldurl/?$ /newurl/ [R=301,L]
</IfModule><IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule ^oldurl/?$ /newurl/ [R=301,L]
</IfModule>
```

This is an invalid `.htaccess` file.

It can be mitigated by doing a `gatsby clean` first.

## Expected behaviour

The plugin should overwrite the old .htaccess file in the build directory, rather than appending to it.

**Comment by chmac** [comment] 2022-04-09 14:30
Hmmm, this was by design if I remember correctly, so that an existing `.htaccess` file could be put into `public/` and then it would have the redirects appended on each build. But you're right that if the build is run repeatedly without an existing file, then the contents will be repeated.

I've pushed a minor fix that adds a newline before & after the content, which should mean that even with the repeated output, the `.htaccess` file is valid.

But it's still not an ideal situation. I'd be open to a PR which implements a better solution.

**Comment by chmac** [comment] 2022-04-09 14:39
Updated the readme in another version, will close this, although still open to PRs improving it.

**Closed as completed by chmac** 2022-04-09 14:39 UTC

**Comment by timmb** [comment] 2022-04-11 09:41
I guess this is to support a workflow where someone would be outputting their build to the server? Or is it in case there are multiple plugins writing to the .htaccess.

Probably the simplest solution would be to provide an `append` option in the plugin settings to set this behaviour.

**Comment by chmac** [comment] 2022-04-11 10:23
@timmb Plus, the scenario where you want to have all kinds of existing rules in your .htaccess file, in addition to the redirects for specific pages.

Adding the `append` option would be one approach, but it wouldn't really solve the issue. Nobody wants the rules appended on every single build. That clearly doesn't make sense. Even though that is the current behaviour. I opened a new issue #11 to track this improvement. My best idea so far is to ready `static/.htaccess` and then concatenate that with the rules and output it as part of the build. This seems like it offers the best of both worlds.
